name: deploy addon with pages
on:
  push:
    paths:
      - "frameworks/**"
jobs:
  deploy:
    name: package
    runs-on: ubuntu-latest
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: increment version nmbr
        run: |
          pip install -r pyscripts/requirements.txt
          python pyscripts/increment_version.py
      - name: prepare framework addon
        run: |
          ADDON_DIR="html/ADDON/"
          FRAMEWORKS_DIR="frameworks"
          CUSTOM_FRAMEWORK_FOLDER="customFramework"
          TARGET_ZIP="../${ADDON_DIR}b-vg-framework.zip"
          if [ -d $ADDON_DIR ]; then rm -rf $ADDON_DIR; fi
          mkdir $ADDON_DIR
          cp "${FRAMEWORKS_DIR}/b-vg-addon.xml" $ADDON_DIR
          cd $FRAMEWORKS_DIR
          zip -r $TARGET_ZIP $CUSTOM_FRAMEWORK_FOLDER
          cd ~
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: prepared new addon
      - name: Deploy Online
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./html
