name: html from odd
on:
  push
jobs:
  download:
    name: convert odd
    runs-on: ubuntu-latest
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v3
      - name: send odd get xhtml
        run: |
          output_dir="./html/"
          index_path="${output_dir}index.html"
          css_path="${output_dir}site.css"
          rm -rf "$output_dir"
          mkdir "$output_dir"
          echo "sending post request to teigarage"
          # other post url i found, no clue what it does like with the other
          # 'https://teigarage.tei-c.org/ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/TEI%3Atext%3Axml/xhtml%3Aapplication%3Axhtml%2Bxml/'
          # so we transform via api and write to $index_path
          curl -X 'POST' \
            'https://teigarage.tei-c.org/ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/oddhtml%3Aapplication%3Axhtml%2Bxml/' \
            -F 'fileToConvert=@./odd/b-vg.odd' \
            -o "$index_path"
          # we link local css to retrieved html
          # this is how this is supposed to be done ;)
          sed -i 's/<link rel="stylesheet"/<link rel="stylesheet" type="text\/css" href=".\/site.css"\/><link rel="stylesheet"/g' $index_path
          # we create an css file
          cat > $css_path <<- EOM
            body {
              padding-left: 25%;
              padding-right: 25%;
              max-width: 40rem;
              min-width: 60rem;
            }

            h1 {
              margin-left: 0rem !important;
              color: rgb(58, 58, 58) !important;
            }

            a {
              color: rgb(58, 58, 58) !important;
              text-decoration:none !important;
              font-weight: bolder;
            }
          EOM
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: created new documentation html from odd
      - name: Deploy Online
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./html
