name: html from odd
on:
  push:
  workflow_run:
    workflows: ["update types in odd from baserow dump"]
    types:
      - completed
env:
  HTML_OUTOUT_DIR: ./html/
jobs:
  download:
    name: convert odd
    runs-on: ubuntu-latest
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v3
      - name: send odd get xhtml/rng
        run: |
          index_path="${HTML_OUTOUT_DIR}index.html"
          css_path="${HTML_OUTOUT_DIR}site.css"
          rm -rf "$HTML_OUTOUT_DIR"
          mkdir "$HTML_OUTOUT_DIR"
          echo "sending post request to teigarage"
          curl -X 'POST' \
            'https://teigarage.tei-c.org/ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/oddhtml%3Aapplication%3Axhtml%2Bxml/' \
            -F 'fileToConvert=@./odd/b-vg.odd' \
            -o "$index_path"
          # we link local css to retrieved html
          # this is how this is supposed to be done ;)
          sed -i 's/<link rel="stylesheet"/<link rel="stylesheet" type="text\/css" href=".\/site.css"\/><link rel="stylesheet"/g' $index_path
          # we create a css file
          cat > $css_path <<- EOM
            body {
              padding-left: 25%;
              padding-right: 25%;
              max-width: 40rem;
              min-width: 60rem;
            }

            h1 {
              margin-left: 0rem !important;
              color: rgb(58, 58, 58) !important;
            }

            a {
              color: rgb(58, 58, 58) !important;
              text-decoration:none !important;
              font-weight: bolder;
            }
          EOM
      - name: send odd get rng
        run: |
          rng_output_dir="./rng/"
          index_path="${rng_output_dir}schema.rng"
          rm -rf "$rng_output_dir"
          mkdir "$rng_output_dir"
          echo "sending post request to teigarage"
          curl -X 'POST' \
            'https://teigarage.tei-c.org/ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/relaxng%3Aapplication%3Axml-relaxng/' \
            -F 'fileToConvert=@./odd/b-vg.odd' \
            -o "$index_path"
          cp -r $rng_output_dir $HTML_OUTOUT_DIR
      - name: publish framework addon
        run: |
          git checkout main -- ~/frameworks/customFramework
          ls
          ADDON_DIR="~/html/ADDON/"
          if [ -d $ADDON_DIR ]; then rm -rf $ADDON_DIR & mkdir $ADDON_DIR; fi
          FRAMEWORKS_DIR="~/frameworks"
          CUSTOM_FRAMEWORK_FOLDER="customFramework"
          TARGET_ZIP="${ADDON_DIR}b-vg-framework.zip"
          cd $FRAMEWORKS_DIR
          zip -r $TARGET_ZIP $CUSTOM_FRAMEWORK_FOLDER
          cd ~
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: created new html/rng from odd
      - name: Deploy Online
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./html
